### ISSUE TITLE
Headless 2d image processing example 

### ISSUE THREAD

**Issue by michael1309** [ttddee/ShaderDev#1]
It's a very cool project. A quick question: I am looking for a headless vulkan example to test, where I can pass an image through a buffer (like a cv::Mat image buffer). Then the pipeline runs and an image is returned in a destination buffer. If possible, vertex and fragment shaders should also be included. Is there an example for this? Or does it make more sense to take the implementation idea for this from your code?

E.g. the function should be called like an opencv function for image filtering (like https://docs.opencv.org/master/d4/d13/tutorial_py_filtering.html ).

Any hints are welcome.

**Comment by ttddee** [comment]
Hi!

The way the pipeline is set up it passes a VkImage into a compute shader, processes and outputs the result as a VkImage. If you want to do headless computation you don't need vertex or fragment shaders. 

Within the compute shader you can write any function you want to do operations on the image.

Here is another example that is a little more refined: https://github.com/ttddee/Cascade/blob/master/src/renderer/vulkanrenderer.cpp

**Comment by michael1309** [comment]
Great. Thanks for your hints!

**Comment by michael1309** [comment]
Perhaps you will allow me to ask a small supplementary question in this context.

Let's assume an application wants to process image by image through a Vulkan pipeline in order to filter the image e.g. low-pass and then process it headless. What would be the best approach in principle for you? According to my beginner's understanding, you would then have to exchange the image data via a mapping process and then trigger the processing again. Maybe you have a small implementation hint for me.

**Comment by ttddee** [comment]
Sorry for the late reply.

You would have to copy the image from the CPU to the GPU. You do that by mapping a chunk of GPU-memory and copying the image into it.

Then you can use your image in a compute shader.

The mapping and copying is the expensive part, so you want to keep those operations to a minimum.
